# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Week6Assignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.2.2'
  # Pods for Week6Assignment

end
